replicaCount: 2

image:
  repository: nginx
  tag: "1.25.3"
  pullPolicy: IfNotPresent

containerPort: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
