apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default  # change this to your desired namespace
  labels:
    app: nginx
spec:
  replicas: 2  # number of pods
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
